### ISSUE TITLE
Issue with perf data and the -A option in check_redis.pl

### ISSUE THREAD

**Issue by matt448** [willixix/naglio-plugins#13]
Hi William,

Today I started working with the perf data options in your check_redis plugin and ran into a problem. I initially tried to use the -A option to return everything but Nagios was not recording a .xml or .rrd file. I did a bunch of checking on my Nagios and pnp4nagios configs trying to figure out what was wrong. After not finding anything wrong in my configs I ended up trying the -f option to output the perf data for only the specific items I was testing. With the -f option I immediately started getting a .rrd file. Not sure if I am doing something incorrect or if the -A option is outputting something Nagios isn't liking.

Thanks,

Matt

**Comment by willixix** [comment]
Yes, this is well known. If you look at the source code you will see %KNOWN_STATUS_VARS array at the start of the code defining various variables and what they mean. Some of them are defined as TEXTDATA or TEXTINFO meaning they are not good for including as performance variables. I don't claim that I have listed all the variables for all different versions of redis.You will need to find the one that is a problem from your redis (it would be something that is not a number, which is why PNP could not properly parse it) and exclude it if you want to use -A by itself. You're welcome to email me which one is a problem so I could update array for the future.
